[build-system]
requires = ["setuptools>=56.0.0", "setuptools_scm[toml]~=7.0"]
build-backend = "setuptools.build_meta"

[tool.black]
# The default is just fine

[tool.isort]
profile = "black"


[tool.setuptools_scm]
write_to = "metricq_sink_websocket/version.py"
